<?php 
$_1p21_sm_opts_fields = array(
	'key' => 'group_9999999999999',
	'title' => 'Sidebars',
	'fields' => array(
		array(
			'key' => 'field_5d7959d3fc885',
			'label' => 'Settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d795a16fc886',
			'label' => 'Widget Class',
			'name' => '_1p21_sm_widget_class',
			'type' => 'text',
			'instructions' => 'classes to append to widget instances',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_column' => 0,
			'show_column_sortable' => 0,
			'show_column_weight' => 1000,
			'allow_quickedit' => 0,
			'allow_bulkedit' => 0,
		),
		array(
			'key' => 'field_5d795dbdebd7c',
			'label' => 'Title Class',
			'name' => '_1p21_sm_title_class',
			'type' => 'text',
			'instructions' => 'classes to add on sidebar titles',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_column' => 0,
			'show_column_sortable' => 0,
			'show_column_weight' => 1000,
			'allow_quickedit' => 0,
			'allow_bulkedit' => 0,
		),
		array(
			'key' => 'field_5d795e34ebd7d',
			'label' => 'Title Tag',
			'name' => '_1p21_sm_title_tag',
			'type' => 'text',
			'instructions' => 'html tag for sidebar titles',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'h3',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_column' => 0,
			'show_column_sortable' => 0,
			'show_column_weight' => 1000,
			'allow_quickedit' => 0,
			'allow_bulkedit' => 0,
		),
		array(
			'key' => 'field_5cc09834f5834',
			'label' => 'Subdirectory Sidebars',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cc09842f5835',
			'label' => 'Sidebars',
			'name' => '_1p21_sm_sidebars',
			'type' => 'repeater',
			'instructions' => 'Set up default sidebars for pages and its descendants',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5cc0984cf5836',
					'label' => 'Sidebar Name',
					'name' => 'sidebar_name',
					'type' => 'text',
					'instructions' => 'Must be unique',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5cc098e5f5838',
					'label' => 'Page',
					'name' => 'page',
					'type' => 'post_object',
					'instructions' => 'Page that will default itself and its descendants to this sidebar instead of the real default sidebar',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'id',
					'show_column' => 0,
					'show_column_weight' => 1000,
					'ui' => 1,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'sidebar-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
);