<?php 

$_1p21_sm_page_fields = array(
	'key' => 'group_5c366a793a9df',
	'title' => 'Custom Sidebar',
	'fields' => array(
		array(
			'key' => 'field_5c36777f31fd1',
			'label' => 'Sidebar Menu Title',
			'name' => '_1p21_sm_title',
			'type' => 'text',
			'instructions' => 'defaults to \'Practice Areas\'',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_column' => 1,
			'show_column_sortable' => 1,
			'show_column_weight' => 1000,
			'allow_quickedit' => 1,
			'allow_bulkedit' => 1,
		),
		array(
			'key' => 'field_5c366a82c27f7',
			'label' => 'Sidebar Menu',
			'name' => '_1p21_sm_menu',
			'type' => 'nav_menu',
			'instructions' => 'Select sidebar menu. if left blank, will default to default sidebar',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'save_format' => 'id',
			'container' => 'div',
			'allow_null' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'allow_quickedit' => 1,
			'allow_bulkedit' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
);